export const SET_ESTABLISHMENT_DATA = "SET_ESTABLISHMENT_DATA";
export const SET_MENU = "SET_MENU";
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const INCREASE_PRODUCT = 'INCREASE_PRODUCT';
export const DECREASE_PRODUCT = 'DECREASE_PRODUCT';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const RESET = 'RESET';